version: '3'
services:
  backend:
    container_name: backend
    image: getjv/php7.2
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - HTTPD_SERVER_NAME=local
      - HTTPD_DOCUMENT_ROOT_CONTEXT=public
    links:
      - mysql
      - mongo
  mysql:
    container_name: mysql
    image: getjv/mysql
    restart: always
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo

      

     
     